### ISSUE TITLE
Upload on Modrinth Please

### ISSUE THREAD

**Issue by sternschnaube** [vlad2305m/Anaglyph-fabric#3]
https://modrinth.com/

**Comment by vlad2305m** [comment]
I will not maintain a second mod page. You can get it from github releases if you don't agree with CurseForge rules.

**Comment by sternschnaube** [comment]
Hello, a bit sad but I understand your point.
Bad that the chance is missing for another big audience, to see and use that mod.
(Maybe create it one time and lead in the description to Curse/GitHub for regular updates. The trick does it.)

**Comment by vlad2305m** [comment]
This mod is free for distribution (with credit (`Copyright (c) 2022 vlad2305m GNU GPLv3`) ). You can make a page for it if you want to ;)
