### ISSUE TITLE
Don't leave, plz!

### ISSUE THREAD

**Issue by idkwidsb** [vlad2305m/Anaglyph-fabric#5]
plz update this mod to 1.19.4+(like 1.20.1), that's importent for some players just like me.
It's useful and meaningful i think. Mojang left it, and this makes me sad. I hope you can continue working on it. And thanks a lot!     : )    

(i'm sorry am not in english...)

**Comment by vlad2305m** [comment]
Thanks for caring
Here you go

**Comment by idkwidsb** [comment]
thanks a lot!!!
  : )
